<?php
session_start();

// Đường dẫn cơ bản
$basePath = __DIR__;

// Kiểm tra session
if (!isset($_SESSION['user_code']) || empty($_SESSION['user_code'])) {
    echo "User session is invalid. Please login again.";
    exit;
}

// Lấy giá trị từ session
$userCode = $_SESSION['user_code'];
$food = $_SESSION[$userCode] ?? null;

if (empty($food)) {
    echo "No food item specified. Please provide a valid input.";
    exit;
}

// Xử lý script Python và đọc file kết quả
try {
    $pythonPath = "/usr/bin/python3"; // Đường dẫn Python
    $testAIScript = escapeshellcmd("$pythonPath testAI.py");
    $filterScript = escapeshellcmd("$pythonPath filter.py");

    // Thực thi script Python
    shell_exec("$testAIScript " . escapeshellarg($food));
    shell_exec($filterScript);

    // Đọc file kết quả
    $filePath = "./answerByAI1.txt";
    if (!file_exists($filePath)) {
        throw new Exception("Result file not found.");
    }

    $content = file_get_contents($filePath);
    if ($content === false) {
        throw new Exception("Cannot read content from result file.");
    }
} catch (Exception $e) {
    $content = "An error occurred: " . htmlspecialchars($e->getMessage());
}

// Xuất giao diện HTML
echo <<<HTML
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>AI Result</title>
    <link href="https://fonts.googleapis.com/css2?family=Poppins:wght@300;400;600&display=swap" rel="stylesheet">
    <style>
        body {
            font-family: 'Poppins', sans-serif;
            margin: 0;
            padding: 0;
            background: linear-gradient(135deg, #eef2f3, #d9e4f5);
            color: #333;
            display: flex;
            align-items: center;
            justify-content: center;
            min-height: 100vh;
        }
        .container {
            max-width: 800px;
            margin: 20px auto;
            padding: 30px;
            background-color: white;
            border-radius: 15px;
            box-shadow: 0 8px 20px rgba(0, 0, 0, 0.2);
            text-align: center;
            animation: fadeIn 1s ease;
        }
        @keyframes fadeIn {
            from { opacity: 0; transform: translateY(20px); }
            to { opacity: 1; transform: translateY(0); }
        }
        h1 {
            font-size: 2.5em;
            margin-bottom: 15px;
            color: #4a90e2;
            text-shadow: 2px 2px 6px rgba(0, 0, 0, 0.1);
        }
        p {
            font-size: 1.1em;
            color: #666;
            margin-bottom: 20px;
        }
        pre {
            background-color: #f8f9fa;
            padding: 20px;
            border-radius: 10px;
            box-shadow: inset 0 4px 6px rgba(0, 0, 0, 0.05);
            overflow-x: auto;
            white-space: pre-wrap;
            font-size: 1em;
            line-height: 1.6;
            color: #444;
            text-align: left;
        }
        .btn {
            display: inline-block;
            margin-top: 20px;
            padding: 12px 30px;
            text-decoration: none;
            color: white;
            background: linear-gradient(135deg, #6a11cb, #2575fc);
            border-radius: 30px;
            font-size: 1.1em;
            font-weight: bold;
            transition: all 0.3s ease;
        }
        .btn:hover {
            background: linear-gradient(135deg, #4ade80, #38bdf8);
            transform: scale(1.1);
            box-shadow: 0 8px 15px rgba(0, 0, 0, 0.2);
        }
        .icon {
            font-size: 60px;
            margin-bottom: 20px;
            color: #2575fc;
        }
        .footer {
            margin-top: 20px;
            font-size: 0.9em;
            color: #888;
        }
        .footer span {
            font-weight: bold;
        }
    </style>
</head>
<body>
    <div class="container">
        <div class="icon">📄</div>
        <h1>Your Result</h1>
        <p>This is the output generated by our calculation based on your input:</p>
        <pre>
HTML;

// Hiển thị nội dung từ file
echo htmlspecialchars($content);

echo <<<HTML
        </pre>
        <a href="../../index.html" class="btn">Go Back</a>
        <div class="footer">&copy; 2025 <span>Nice Try Team</span>. Powered by our team.</div>
    </div>
</body>
</html>
HTML;
?>
